application: notes-autosave-example
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /server/.*
  script: code.app

- url: (.*)/
  static_files: app\1/index.html
  upload: app
  login: required

- url: (.*)
  static_files: app\1
  upload: app
  login: required

